import { Metadata } from "next"

import Footer from "../components/footer"
import Header from "../components/header"

export const metadata: Metadata = {
  title: {
    default: 'Next.js Training 2025 - Marvin',
    template: '%s | Next.js Training 2025 - Marvin',
    //absolute: '', Move this to a specific page if needed. ex: blog page
  },
  description: 'Generated by Next.js',
}

export default function MainLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
