import { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import Footer from "../components/footer"
import Header from "../components/header"
import Navigation from "../components/navigation";
import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: 'Next.js Training 2025 - Marvin',
    template: '%s | Next.js Training 2025 - Marvin',
    //absolute: '', Move this to a specific page if needed. ex: blog page
  },
  description: 'Generated by Next.js',
}

export default function MainLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Navigation />
        <ErrorWrapper>
          {children}
        </ErrorWrapper>
        <Footer />
      </body>
    </html>
  )
}
